# +----------------------------------------------------+
# <                Welcome to Quasar                   >
# <          Minecraft Rust & Zombie integration       >
# <                 Customise below!                   >
# +----------------------------------------------------+